version: "3"
services:
  discuss:
    build: .
    image: appname
    volumes:
      - .:/app/discuss
    ports:
      - 4000:4000
    environment:
      - MIX_ENV=dev
    depends_on:
      - postgres
    command: mix phx.server

  postgres:
    image: postgres:12.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
